### PR TITLE
(*File).Chmod on Windows

### PR DESCRIPTION
**Pull request by mchtech**
https://github.com/golang/go/blob/bba88467f86472764a656e61f5f3265ed6853692/src/syscall/syscall_windows.go#L1094

os.Chmod always return syscall.EWINDOWS error on Windows.

### CODE REVIEW

**Comment by peterbourgon** [comment]
How do you change file perms on Windows, then?

**Comment by mchtech** [comment]
golang does not support `chmod` on Windows (so far) and `ioutil.TempFile` always creates file with 0600.
So, one solution is to create the tmpfile with specified `FilePerm` directly.

**Comment by peterbourgon** [comment]
[os.Chmod works fine on Windows](https://golang.org/pkg/os/#Chmod), it just requires a restricted set of file modes. If you're using diskv on Windows, you can change diskv.FilePerm to one of those supported modes.

**Comment by peterbourgon** [comment]
@mchtech Will that solve your problem?

**Comment by mchtech** [comment]
It seems a problem of golang 😂

[os.Chmod](https://github.com/golang/go/blob/a9a78b7005f400e52d8891b01458539e801cf8ad/src/os/file_posix.go#L79) works fine on Windows, but[ (*File).Chmod ](https://github.com/golang/go/blob/a9a78b7005f400e52d8891b01458539e801cf8ad/src/os/file_posix.go#L90)will return syscall.EWINDOWS.

on Windows:
 - os.Chmod -> syscall.Chmod -> Windows API SetFileAttributes
 - (*File).Chmod -> (*File).pfd.Fchmod -> (*FD).fchmod -> syscall.Fchmod -> return syscall.EWINDOWS

**Comment by peterbourgon** [comment]
Please read the documentation I linked and try the solution I offered.

**Comment by mchtech** [comment]
I just tested it on Windows:
os.Chmod works fine on Windows and does not return any error
but [(*File).Chmod](https://github.com/peterbourgon/diskv/blob/0be1b92a6df0e4f5cb0a5d15fb7f643d0ad93ce6/diskv.go#L211) not

**Comment by peterbourgon** [comment]
OK, I believe this is safe.

**Pull request merged**
