### PR TITLE
Update google/btree to 1.0.1 with minor fixes.

### PR DESCRIPTION
**Pull request by iredmail**

### CODE REVIEW

**Comment by peterbourgon** [comment]
What are the fixes? Can you write a unit test which fails on master and passes on this PR?

**Comment by iredmail** [comment]
Sorry about the confusion, i mean golang/btree 1.0.1 itself has some minor fixes. I don't mean this PR fixes diskv issues.

**Comment by peterbourgon** [comment]
Yes, I understand. Do any of those fixes impact this project?

**Comment by iredmail** [comment]
No. ok, feel free to close the PR if you don't like this.

**Pull request closed without merging**
